#! /usr/bin/env php
<?php
	$TTL = 60;
	$user=exec('whoami');

	$messageFile = (isset($argv[1]) ? $argv[1] : null);
	$message = (isset($argv[1]) ? file_get_contents($messageFile) : "");

	$issueIdPattern = "/#(\\d{1,32})/";
    preg_match($issueIdPattern, $message, $matches);
    $issueId = (isset($matches[1])) ? $matches[1] : null;

	if ( is_null($issueId) ) {
		echo "-----------------------------------------" . PHP_EOL;
		echo "No issue number specified in commit message" . PHP_EOL;
		echo "-----------------------------------------" . PHP_EOL . PHP_EOL;
		exit(1);
	}

	$cached = "/tmp/contenta-issues-$user.json";
	$use_cache = false;
	if (@file_exists($cached) && filemtime($cached) > (time() - ($TTL))) {
		$use_cache = true;
	}

	if ( $use_cache == true ) {
		$data = file_get_contents($cached);
		if ( $data != false ) {
			$json = json_decode($data, true);
			if ( json_last_error() != 0 ) {
				@unlink( $cached );
			}
		}
		else {
			@unlink( $cached );
		}
	}

	if (isset($json) == false) {
		$url = "https://api.github.com/repos/vitolibrarius/contenta/issues";
		$context = array(
			'http' => array(
				'ignore_errors' => true,
				'method' => "GET",
				'header'=>	"Accept-language: en\r\n" .
							"User-Agent: PHP/5.2.9\r\n",
							"Content-Type: application/json\r\n"
			)
		);


		$data = file_get_contents($url, false, stream_context_create($context));
		if ( $data != false ) {
			$json = json_decode($data, true);
			if ( json_last_error() == 0 ) {
				file_put_contents( $cached, json_encode($json, JSON_PRETTY_PRINT) );
			}
		}
	}

	$issueMatch = null;
	if (isset($json) && is_array($json)) {
		foreach( $json as $issue ) {
			if ( $issue['number'] == $issueId ) {
				$issueMatch = $issue;
				break;
			}
		}
	}

	if ( is_null($issueMatch) ) {
		echo "-----------------------------------------" . PHP_EOL;
		echo "Issue #" . $issueId . " was not found in list of open issues" . PHP_EOL;
		echo "-----------------------------------------" . PHP_EOL . PHP_EOL;
		exit(1);
	}

?>
